spring:
  application:
    name: VPPSystem

  datasource:
    url: jdbc:mysql://localhost:3306/vppsystemdb
    username: root
    password: root1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

# /api-docs endpoint custom path

#springdoc:
#  api-docs:
#    path: /api-docs
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true